import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// 1. Bundle the editor for the browser and inline it into the HTML. Inlining
//    keeps the app self-contained, so it needs no CSP allowance for a CDN.
const ui = await build({
  entryPoints: [join(root, "src/ui/app.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome120", "safari17"],
  minify: true,
  write: false,
});

const js = ui.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const html = (await readFile(join(root, "src/ui/index.html"), "utf8")).replace("/*__APP_JS__*/", () => js);

await mkdir(join(root, "dist/ui"), { recursive: true });
await writeFile(join(root, "dist/ui/index.html"), html, "utf8");

// 2. Bundle the server itself. Dependencies stay external so the MCP SDK keeps
//    its own module resolution.
await build({
  entryPoints: [join(root, "src/index.ts")],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  packages: "external",
  outfile: join(root, "dist/index.js"),
});

// 3. Ship the workflow guide next to the server, and generate the Claude Code
//    slash command from the same source so the two can never drift.
const guide = await readFile(join(root, "prompts/pptgo.md"), "utf8");
await mkdir(join(root, "dist/prompts"), { recursive: true });
await writeFile(join(root, "dist/prompts/pptgo.md"), guide, "utf8");

await mkdir(join(root, ".claude/commands"), { recursive: true });
await writeFile(
  join(root, ".claude/commands/pptgo.md"),
  `---
description: Author or revise a deck with pptgo, preview it, and export native PPTX
argument-hint: [what to make or change]
---

<!-- Generated by scripts/build.mjs from prompts/pptgo.md — edit that file instead. -->

${guide}
---

Request: $ARGUMENTS
`,
  "utf8",
);

// 4. Also emit the modules unbundled, so the dev host can import them directly.
await build({
  entryPoints: [
    join(root, "src/config.ts"),
    join(root, "src/deck.ts"),
    join(root, "src/pptmaster.ts"),
    join(root, "src/server.ts"),
  ],
  bundle: false,
  format: "esm",
  platform: "node",
  target: "node20",
  outdir: join(root, "dist/lib"),
});

console.log(`built dist/index.js and dist/ui/index.html (${(html.length / 1024).toFixed(1)} KB)`);
